# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pentavalent <- function(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc, epi_A, epi_R) {
    .Call(`_mmcv_pentavalent`, t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc, epi_A, epi_R)
}

PentaSt <- function(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc) {
    .Call(`_mmcv_PentaSt`, t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc)
}

PentaDyn <- function(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc) {
    .Call(`_mmcv_PentaDyn`, t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc)
}

PentaLongV <- function(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc, epi_A, epi_R) {
    .Call(`_mmcv_PentaLongV`, t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc, epi_A, epi_R)
}

rcpp_hello_world <- function() {
    .Call(`_mmcv_rcpp_hello_world`)
}

