// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pentavalent
List pentavalent(double t, NumericVector x, NumericVector params, NumericMatrix Cm, NumericVector mu, double max_age, NumericVector B, NumericVector ir_A, NumericVector ir_R, NumericVector stoc, NumericVector epi_A, NumericVector epi_R);
RcppExport SEXP _mmcv_pentavalent(SEXP tSEXP, SEXP xSEXP, SEXP paramsSEXP, SEXP CmSEXP, SEXP muSEXP, SEXP max_ageSEXP, SEXP BSEXP, SEXP ir_ASEXP, SEXP ir_RSEXP, SEXP stocSEXP, SEXP epi_ASEXP, SEXP epi_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Cm(CmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type max_age(max_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_A(ir_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_R(ir_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stoc(stocSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epi_A(epi_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epi_R(epi_RSEXP);
    rcpp_result_gen = Rcpp::wrap(pentavalent(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc, epi_A, epi_R));
    return rcpp_result_gen;
END_RCPP
}
// PentaSt
List PentaSt(double t, NumericVector x, NumericVector params, NumericMatrix Cm, NumericVector mu, double max_age, double B, NumericVector ir_A, NumericVector ir_R, NumericVector stoc);
RcppExport SEXP _mmcv_PentaSt(SEXP tSEXP, SEXP xSEXP, SEXP paramsSEXP, SEXP CmSEXP, SEXP muSEXP, SEXP max_ageSEXP, SEXP BSEXP, SEXP ir_ASEXP, SEXP ir_RSEXP, SEXP stocSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Cm(CmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type max_age(max_ageSEXP);
    Rcpp::traits::input_parameter< double >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_A(ir_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_R(ir_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stoc(stocSEXP);
    rcpp_result_gen = Rcpp::wrap(PentaSt(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc));
    return rcpp_result_gen;
END_RCPP
}
// PentaDyn
List PentaDyn(double t, NumericVector x, NumericVector params, NumericMatrix Cm, NumericVector mu, double max_age, NumericVector B, NumericVector ir_A, NumericVector ir_R, NumericVector stoc);
RcppExport SEXP _mmcv_PentaDyn(SEXP tSEXP, SEXP xSEXP, SEXP paramsSEXP, SEXP CmSEXP, SEXP muSEXP, SEXP max_ageSEXP, SEXP BSEXP, SEXP ir_ASEXP, SEXP ir_RSEXP, SEXP stocSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Cm(CmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type max_age(max_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_A(ir_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_R(ir_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stoc(stocSEXP);
    rcpp_result_gen = Rcpp::wrap(PentaDyn(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc));
    return rcpp_result_gen;
END_RCPP
}
// PentaLongV
List PentaLongV(double t, NumericVector x, NumericVector params, NumericMatrix Cm, NumericVector mu, double max_age, NumericVector B, NumericVector ir_A, NumericVector ir_R, NumericVector stoc, NumericVector epi_A, NumericVector epi_R);
RcppExport SEXP _mmcv_PentaLongV(SEXP tSEXP, SEXP xSEXP, SEXP paramsSEXP, SEXP CmSEXP, SEXP muSEXP, SEXP max_ageSEXP, SEXP BSEXP, SEXP ir_ASEXP, SEXP ir_RSEXP, SEXP stocSEXP, SEXP epi_ASEXP, SEXP epi_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Cm(CmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type max_age(max_ageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_A(ir_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ir_R(ir_RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stoc(stocSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epi_A(epi_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type epi_R(epi_RSEXP);
    rcpp_result_gen = Rcpp::wrap(PentaLongV(t, x, params, Cm, mu, max_age, B, ir_A, ir_R, stoc, epi_A, epi_R));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _mmcv_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mmcv_pentavalent", (DL_FUNC) &_mmcv_pentavalent, 12},
    {"_mmcv_PentaSt", (DL_FUNC) &_mmcv_PentaSt, 10},
    {"_mmcv_PentaDyn", (DL_FUNC) &_mmcv_PentaDyn, 10},
    {"_mmcv_PentaLongV", (DL_FUNC) &_mmcv_PentaLongV, 12},
    {"_mmcv_rcpp_hello_world", (DL_FUNC) &_mmcv_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_mmcv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
